import os

DOCKER_REGISTRY = os.getenv('DOCKER_REGISTRY')
DOCKER_REGISTRY_USERNAME = os.getenv('DOCKER_REGISTRY_USERNAME')
DOCKER_REGISTRY_PASSWORD = os.getenv('DOCKER_REGISTRY_PASSWORD')

print(DOCKER_REGISTRY)
print(DOCKER_REGISTRY_USERNAME)
print(DOCKER_REGISTRY_PASSWORD)
