name: Reusable Workflow Test

on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check Value
        run: |
            cat $env_file
            cd webapp/client
            ls -la ${{ github.workspace }}/$env_file
            sed -i -e 's,ETBOX_API_ENV_URL,${{ vars.REACT_APP_API_URL }},g' ${{ github.workspace }}/$env_file
            cat ${{ github.workspace }}/$env_file
        env:
            env_file: webapp/client/.env.production