name: Reusable Workflow Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check Value
        run: |
          cat $env_file
          cd webapp/client
          ls -la ${{ github.workspace }}/webapp/client/.env.production
          sed -i -e 's,ETBOX_API_ENV_URL,${{ vars.REACT_APP_API_URL }},g' ${{ github.workspace }}/webapp/client/.env.production
          cat ${{ github.workspace }}/webapp/client/.env.production
        env:
            env_file: webapp/client/.env.production