name: Reusable Workflow Test

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            secrets_vars:
                required: true
                type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check Value
        run: |
            echo "Environment you working is:"
            echo ${{ github.event.inputs.environment }}
            echo "Secrets and Variable you working is:"
            echo ${{ vars.REACT_APP_API_URL }}