name: Reusable Workflow Test

on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        env_file: 
            required: true
            type: string
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check Value
        run: |
          cat ${{ inputs.env_file}}
          cd webapp/client
          ls -la ${{ github.workspace }}/webapp/client/.env.${{ inputs.env_file}}
          sed -i -e 's,ETBOX_API_ENV_URL,${{ vars.REACT_APP_API_URL }},g' ${{ github.workspace }}/webapp/client/.env.${{ inputs.env_file}}
          cat ${{ github.workspace }}/webapp/client/.env.${{ inputs.env_file}}
        env:
            env_file: webapp/client/.env.${{ inputs.env_file}}