name: Reusable Workflow Test

on:
  workflow_call:
    inputs:
      field:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check Value
        run: |
          echo "Field you are working in is:"
          echo ${{ github.event.inputs.field }}
          echo "Environment your working on is:"
          echo ${{ github.event.inputs.environment }}
          echo "Variable value is:"
          echo ${{ vars.REACT_APP_API_URL[environment] }}