name: CI on Successful PR Merge to Main

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if it's a merge to main
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          echo "This is a successful merge to the main branch."
          echo "Add your build and test steps here"