name: Build and Deploy

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure NGINX
      run: |
        sudo apt-get update
        sudo apt-get install nginx