name: CI on Pull Request to Main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test environment Pull Request Trigger
        run: |
            echo "Workflow works for Test environment Pull Request trigger"