name: Use Main Branch Reusable Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - development
jobs:
    MainBranchReusable:
        uses: Enzo-Vasquez/Test/.github/workflows/_main_reusable.yml@main
