name: Use Main Branch Reusable Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - development
jobs:
    MainBranchReusable:
        uses: .github/workflows/_reusable_workflow.yml@main
